# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/ntu120/xsub/val_data_bone_motion.npy
  label_path: ./data/ntu120/xsub/val_label.pkl
  debug: False

# model
model: model.rsgcn.Model
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

# test
phase: test
device: [0,1,2]
test_batch_size: 256
weights: ./weights/ntu120_cs_rsgcn_bone_motion-51-54600.pt

work_dir: ./work_dir/ntu120/xsub/rsgcn_test_bone_motion
model_saved_name: ./runs/ntu120_cs_rsgcn_test_bone_motion
save_score: True