work_dir: ./work_dir/kinetics/rsgcn_joint
model_saved_name: ./runs/ki_rsgcn_joint

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_shift: False
  random_move: False
  window_size: 52
  normalization: False
  data_path: ./data/kinetics/train_data_joint.npy
  label_path: ./data/kinetics/train_label.pkl
  debug: False

test_feeder_args:
  data_path: ./data/kinetics/val_data_joint.npy
  label_path: ./data/kinetics/val_label.pkl

# model
model: model.rsgcn.Model
model_args:
  num_class: 10
    num_point: 20
    num_person: 1
    graph: graph.ntu_rgb_d.Graph
    graph_args:
      labeling_mode: 'spatial'
  alpha: 0.2e-5


#optim
weight_decay: 0.0001
base_lr: 0.1
step: [45, 55]

# training
device: [0, 1]
batch_size: 128
test_batch_size: 256
num_epoch: 70
nesterov: True
only_train_part: True
only_train_epoch: 5



