# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/ntu/xview/val_data_bone.npy
  label_path: ./data/ntu/xview/val_label.pkl
  debug: False

# model
model: model.rsgcn.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'


# test 
phase: test
device: [0,1]
test_batch_size: 256
weights: ./weights/ntu_cv_rsgcn_bone-56-33516.pt
work_dir: ./work_dir/ntu/xview/rsgcn_test_bone
model_saved_name: ./runs/ntu_cv_rsgcn_test_bone
save_score: True