# feeder
feeder: feeders.feeder.Feeder_UCLA
test_feeder_args:
  data_path: bone_motion
  label_path: val
  debug: False

# model
model: model.rsgcn.Model
model_args:
  num_class: 10
  num_point: 20
  num_person: 1
  alpha: 0.5e-4
  graph: graph.nw_ucla.Graph
  graph_args:
    labeling_mode: 'spatial'


# test
phase: test
device: [0,1]
test_batch_size: 64
weights: ./weights/nw_ucla_rsgcn_bone_motion-57-3654.pt

work_dir: ./work_dir/nw_ucla/rsgcn_test_bone_motion
model_saved_name: ./runs/nw_ucla_rsgcn_test_bone_motion
save_score: True