work_dir: ./work_dir/nw_ucla/rsgcn_joint_motion
model_saved_name: ./runs/nw_ucla_rsgcn_joint_motion
# feeder
feeder: feeders.feeder.Feeder_UCLA
train_feeder_args:
  data_path: joint_motion
  label_path: train
  debug: False
  random_choose: True
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: joint_motion
  label_path: val

# model
model: model.rsgcn.Model
model_args:
  num_class: 10
  num_point: 20
  num_person: 1
  alpha: 0.5e-4
  graph: graph.nw_ucla.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0002
base_lr: 0.1
step: [40, 50]

# training
device: [0, 1]
batch_size: 16
test_batch_size: 64
num_epoch: 60
nesterov: True
only_train_part: True
only_train_epoch: 2
